//-----------------------------------------------
//
//	This file is part of the Siv3D Engine.
//
//	Copyright (c) 2008-2023 Ryo Suzuki
//	Copyright (c) 2016-2023 OpenSiv3D Project
//
//	Licensed under the MIT License.
//
//-----------------------------------------------

# include <Siv3D/Script.hpp>
# include <Siv3D/ColorHSV.hpp>

namespace s3d
{
	using namespace AngelScript;

	void RegisterPalette(asIScriptEngine* engine)
	{
		[[maybe_unused]] int32 r = 0;

		r = engine->SetDefaultNamespace("Palette"); assert(r >= 0);
		{
			r = engine->RegisterGlobalProperty("const Color Black", (void*)&Palette::Black); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Dimgray", (void*)&Palette::Dimgray); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Dimgrey", (void*)&Palette::Dimgrey); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Gray", (void*)&Palette::Gray); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Grey", (void*)&Palette::Grey); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkgray", (void*)&Palette::Darkgray); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkgrey", (void*)&Palette::Darkgrey); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Silver", (void*)&Palette::Silver); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lightgray", (void*)&Palette::Lightgray); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lightgrey", (void*)&Palette::Lightgrey); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Gainsboro", (void*)&Palette::Gainsboro); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Whitesmoke", (void*)&Palette::Whitesmoke); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color White", (void*)&Palette::White); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Snow", (void*)&Palette::Snow); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Ghostwhite", (void*)&Palette::Ghostwhite); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Floralwhite", (void*)&Palette::Floralwhite); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Linen", (void*)&Palette::Linen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Antiquewhite", (void*)&Palette::Antiquewhite); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Papayawhip", (void*)&Palette::Papayawhip); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Blanchedalmond", (void*)&Palette::Blanchedalmond); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Bisque", (void*)&Palette::Bisque); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Moccasin", (void*)&Palette::Moccasin); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Navajowhite", (void*)&Palette::Navajowhite); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Peachpuff", (void*)&Palette::Peachpuff); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Mistyrose", (void*)&Palette::Mistyrose); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lavenderblush", (void*)&Palette::Lavenderblush); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Seashell", (void*)&Palette::Seashell); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Oldlace", (void*)&Palette::Oldlace); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Ivory", (void*)&Palette::Ivory); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Honeydew", (void*)&Palette::Honeydew); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Mintcream", (void*)&Palette::Mintcream); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Azure", (void*)&Palette::Azure); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Aliceblue", (void*)&Palette::Aliceblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lavender", (void*)&Palette::Lavender); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lightsteelblue", (void*)&Palette::Lightsteelblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lightslategray", (void*)&Palette::Lightslategray); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lightslategrey", (void*)&Palette::Lightslategrey); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Slategray", (void*)&Palette::Slategray); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Slategrey", (void*)&Palette::Slategrey); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Steelblue", (void*)&Palette::Steelblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Royalblue", (void*)&Palette::Royalblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Midnightblue", (void*)&Palette::Midnightblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Navy", (void*)&Palette::Navy); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkblue", (void*)&Palette::Darkblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Mediumblue", (void*)&Palette::Mediumblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Blue", (void*)&Palette::Blue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Dodgerblue", (void*)&Palette::Dodgerblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Cornflowerblue", (void*)&Palette::Cornflowerblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Deepskyblue", (void*)&Palette::Deepskyblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lightskyblue", (void*)&Palette::Lightskyblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Skyblue", (void*)&Palette::Skyblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lightblue", (void*)&Palette::Lightblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Powderblue", (void*)&Palette::Powderblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Paleturquoise", (void*)&Palette::Paleturquoise); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lightcyan", (void*)&Palette::Lightcyan); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Cyan", (void*)&Palette::Cyan); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Aqua", (void*)&Palette::Aqua); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Turquoise", (void*)&Palette::Turquoise); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Mediumturquoise", (void*)&Palette::Mediumturquoise); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkturquoise", (void*)&Palette::Darkturquoise); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lightseagreen", (void*)&Palette::Lightseagreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Cadetblue", (void*)&Palette::Cadetblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkcyan", (void*)&Palette::Darkcyan); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Teal", (void*)&Palette::Teal); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkslategray", (void*)&Palette::Darkslategray); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkslategrey", (void*)&Palette::Darkslategrey); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkgreen", (void*)&Palette::Darkgreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Green", (void*)&Palette::Green); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Forestgreen", (void*)&Palette::Forestgreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Seagreen", (void*)&Palette::Seagreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Mediumseagreen", (void*)&Palette::Mediumseagreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Mediumaquamarine", (void*)&Palette::Mediumaquamarine); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkseagreen", (void*)&Palette::Darkseagreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Aquamarine", (void*)&Palette::Aquamarine); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Palegreen", (void*)&Palette::Palegreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lightgreen", (void*)&Palette::Lightgreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Springgreen", (void*)&Palette::Springgreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Mediumspringgreen", (void*)&Palette::Mediumspringgreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lawngreen", (void*)&Palette::Lawngreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Chartreuse", (void*)&Palette::Chartreuse); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Greenyellow", (void*)&Palette::Greenyellow); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lime", (void*)&Palette::Lime); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Limegreen", (void*)&Palette::Limegreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Yellowgreen", (void*)&Palette::Yellowgreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkolivegreen", (void*)&Palette::Darkolivegreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Olivedrab", (void*)&Palette::Olivedrab); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Olive", (void*)&Palette::Olive); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkkhaki", (void*)&Palette::Darkkhaki); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Palegoldenrod", (void*)&Palette::Palegoldenrod); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Cornsilk", (void*)&Palette::Cornsilk); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Beige", (void*)&Palette::Beige); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lightyellow", (void*)&Palette::Lightyellow); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lightgoldenrodyellow", (void*)&Palette::Lightgoldenrodyellow); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lemonchiffon", (void*)&Palette::Lemonchiffon); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Wheat", (void*)&Palette::Wheat); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Burlywood", (void*)&Palette::Burlywood); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Tan", (void*)&Palette::Tan); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Khaki", (void*)&Palette::Khaki); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Yellow", (void*)&Palette::Yellow); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Gold", (void*)&Palette::Gold); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Orange", (void*)&Palette::Orange); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Sandybrown", (void*)&Palette::Sandybrown); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkorange", (void*)&Palette::Darkorange); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Goldenrod", (void*)&Palette::Goldenrod); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Peru", (void*)&Palette::Peru); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkgoldenrod", (void*)&Palette::Darkgoldenrod); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Chocolate", (void*)&Palette::Chocolate); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Sienna", (void*)&Palette::Sienna); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Saddlebrown", (void*)&Palette::Saddlebrown); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Maroon", (void*)&Palette::Maroon); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkred", (void*)&Palette::Darkred); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Brown", (void*)&Palette::Brown); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Firebrick", (void*)&Palette::Firebrick); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Indianred", (void*)&Palette::Indianred); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Rosybrown", (void*)&Palette::Rosybrown); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darksalmon", (void*)&Palette::Darksalmon); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lightcoral", (void*)&Palette::Lightcoral); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Salmon", (void*)&Palette::Salmon); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lightsalmon", (void*)&Palette::Lightsalmon); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Coral", (void*)&Palette::Coral); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Tomato", (void*)&Palette::Tomato); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Orangered", (void*)&Palette::Orangered); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Red", (void*)&Palette::Red); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Crimson", (void*)&Palette::Crimson); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Mediumvioletred", (void*)&Palette::Mediumvioletred); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Deeppink", (void*)&Palette::Deeppink); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Hotpink", (void*)&Palette::Hotpink); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Palevioletred", (void*)&Palette::Palevioletred); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Pink", (void*)&Palette::Pink); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Lightpink", (void*)&Palette::Lightpink); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Thistle", (void*)&Palette::Thistle); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Magenta", (void*)&Palette::Magenta); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Fuchsia", (void*)&Palette::Fuchsia); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Violet", (void*)&Palette::Violet); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Plum", (void*)&Palette::Plum); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Orchid", (void*)&Palette::Orchid); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Mediumorchid", (void*)&Palette::Mediumorchid); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkorchid", (void*)&Palette::Darkorchid); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkviolet", (void*)&Palette::Darkviolet); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkmagenta", (void*)&Palette::Darkmagenta); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Purple", (void*)&Palette::Purple); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Indigo", (void*)&Palette::Indigo); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Darkslateblue", (void*)&Palette::Darkslateblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Blueviolet", (void*)&Palette::Blueviolet); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Mediumpurple", (void*)&Palette::Mediumpurple); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Slateblue", (void*)&Palette::Slateblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color Mediumslateblue", (void*)&Palette::Mediumslateblue); assert(r >= 0);
		
			r = engine->RegisterGlobalProperty("const Color DefaultLetterbox", (void*)&Palette::DefaultLetterbox); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const Color DefaultBackground", (void*)&Palette::DefaultBackground); assert(r >= 0);
		}
		r = engine->SetDefaultNamespace(""); assert(r >= 0);

		r = engine->SetDefaultNamespace("Linear::Palette"); assert(r >= 0);
		{
			r = engine->RegisterGlobalProperty("const ColorF Black", (void*)&Linear::Palette::Black); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Dimgray", (void*)&Linear::Palette::Dimgray); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Dimgrey", (void*)&Linear::Palette::Dimgrey); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Gray", (void*)&Linear::Palette::Gray); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Grey", (void*)&Linear::Palette::Grey); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkgray", (void*)&Linear::Palette::Darkgray); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkgrey", (void*)&Linear::Palette::Darkgrey); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Silver", (void*)&Linear::Palette::Silver); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lightgray", (void*)&Linear::Palette::Lightgray); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lightgrey", (void*)&Linear::Palette::Lightgrey); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Gainsboro", (void*)&Linear::Palette::Gainsboro); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Whitesmoke", (void*)&Linear::Palette::Whitesmoke); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF White", (void*)&Linear::Palette::White); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Snow", (void*)&Linear::Palette::Snow); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Ghostwhite", (void*)&Linear::Palette::Ghostwhite); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Floralwhite", (void*)&Linear::Palette::Floralwhite); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Linen", (void*)&Linear::Palette::Linen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Antiquewhite", (void*)&Linear::Palette::Antiquewhite); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Papayawhip", (void*)&Linear::Palette::Papayawhip); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Blanchedalmond", (void*)&Linear::Palette::Blanchedalmond); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Bisque", (void*)&Linear::Palette::Bisque); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Moccasin", (void*)&Linear::Palette::Moccasin); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Navajowhite", (void*)&Linear::Palette::Navajowhite); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Peachpuff", (void*)&Linear::Palette::Peachpuff); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Mistyrose", (void*)&Linear::Palette::Mistyrose); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lavenderblush", (void*)&Linear::Palette::Lavenderblush); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Seashell", (void*)&Linear::Palette::Seashell); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Oldlace", (void*)&Linear::Palette::Oldlace); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Ivory", (void*)&Linear::Palette::Ivory); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Honeydew", (void*)&Linear::Palette::Honeydew); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Mintcream", (void*)&Linear::Palette::Mintcream); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Azure", (void*)&Linear::Palette::Azure); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Aliceblue", (void*)&Linear::Palette::Aliceblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lavender", (void*)&Linear::Palette::Lavender); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lightsteelblue", (void*)&Linear::Palette::Lightsteelblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lightslategray", (void*)&Linear::Palette::Lightslategray); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lightslategrey", (void*)&Linear::Palette::Lightslategrey); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Slategray", (void*)&Linear::Palette::Slategray); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Slategrey", (void*)&Linear::Palette::Slategrey); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Steelblue", (void*)&Linear::Palette::Steelblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Royalblue", (void*)&Linear::Palette::Royalblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Midnightblue", (void*)&Linear::Palette::Midnightblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Navy", (void*)&Linear::Palette::Navy); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkblue", (void*)&Linear::Palette::Darkblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Mediumblue", (void*)&Linear::Palette::Mediumblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Blue", (void*)&Linear::Palette::Blue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Dodgerblue", (void*)&Linear::Palette::Dodgerblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Cornflowerblue", (void*)&Linear::Palette::Cornflowerblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Deepskyblue", (void*)&Linear::Palette::Deepskyblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lightskyblue", (void*)&Linear::Palette::Lightskyblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Skyblue", (void*)&Linear::Palette::Skyblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lightblue", (void*)&Linear::Palette::Lightblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Powderblue", (void*)&Linear::Palette::Powderblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Paleturquoise", (void*)&Linear::Palette::Paleturquoise); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lightcyan", (void*)&Linear::Palette::Lightcyan); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Cyan", (void*)&Linear::Palette::Cyan); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Aqua", (void*)&Linear::Palette::Aqua); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Turquoise", (void*)&Linear::Palette::Turquoise); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Mediumturquoise", (void*)&Linear::Palette::Mediumturquoise); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkturquoise", (void*)&Linear::Palette::Darkturquoise); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lightseagreen", (void*)&Linear::Palette::Lightseagreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Cadetblue", (void*)&Linear::Palette::Cadetblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkcyan", (void*)&Linear::Palette::Darkcyan); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Teal", (void*)&Linear::Palette::Teal); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkslategray", (void*)&Linear::Palette::Darkslategray); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkslategrey", (void*)&Linear::Palette::Darkslategrey); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkgreen", (void*)&Linear::Palette::Darkgreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Green", (void*)&Linear::Palette::Green); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Forestgreen", (void*)&Linear::Palette::Forestgreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Seagreen", (void*)&Linear::Palette::Seagreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Mediumseagreen", (void*)&Linear::Palette::Mediumseagreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Mediumaquamarine", (void*)&Linear::Palette::Mediumaquamarine); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkseagreen", (void*)&Linear::Palette::Darkseagreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Aquamarine", (void*)&Linear::Palette::Aquamarine); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Palegreen", (void*)&Linear::Palette::Palegreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lightgreen", (void*)&Linear::Palette::Lightgreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Springgreen", (void*)&Linear::Palette::Springgreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Mediumspringgreen", (void*)&Linear::Palette::Mediumspringgreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lawngreen", (void*)&Linear::Palette::Lawngreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Chartreuse", (void*)&Linear::Palette::Chartreuse); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Greenyellow", (void*)&Linear::Palette::Greenyellow); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lime", (void*)&Linear::Palette::Lime); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Limegreen", (void*)&Linear::Palette::Limegreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Yellowgreen", (void*)&Linear::Palette::Yellowgreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkolivegreen", (void*)&Linear::Palette::Darkolivegreen); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Olivedrab", (void*)&Linear::Palette::Olivedrab); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Olive", (void*)&Linear::Palette::Olive); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkkhaki", (void*)&Linear::Palette::Darkkhaki); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Palegoldenrod", (void*)&Linear::Palette::Palegoldenrod); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Cornsilk", (void*)&Linear::Palette::Cornsilk); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Beige", (void*)&Linear::Palette::Beige); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lightyellow", (void*)&Linear::Palette::Lightyellow); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lightgoldenrodyellow", (void*)&Linear::Palette::Lightgoldenrodyellow); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lemonchiffon", (void*)&Linear::Palette::Lemonchiffon); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Wheat", (void*)&Linear::Palette::Wheat); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Burlywood", (void*)&Linear::Palette::Burlywood); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Tan", (void*)&Linear::Palette::Tan); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Khaki", (void*)&Linear::Palette::Khaki); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Yellow", (void*)&Linear::Palette::Yellow); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Gold", (void*)&Linear::Palette::Gold); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Orange", (void*)&Linear::Palette::Orange); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Sandybrown", (void*)&Linear::Palette::Sandybrown); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkorange", (void*)&Linear::Palette::Darkorange); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Goldenrod", (void*)&Linear::Palette::Goldenrod); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Peru", (void*)&Linear::Palette::Peru); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkgoldenrod", (void*)&Linear::Palette::Darkgoldenrod); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Chocolate", (void*)&Linear::Palette::Chocolate); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Sienna", (void*)&Linear::Palette::Sienna); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Saddlebrown", (void*)&Linear::Palette::Saddlebrown); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Maroon", (void*)&Linear::Palette::Maroon); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkred", (void*)&Linear::Palette::Darkred); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Brown", (void*)&Linear::Palette::Brown); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Firebrick", (void*)&Linear::Palette::Firebrick); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Indianred", (void*)&Linear::Palette::Indianred); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Rosybrown", (void*)&Linear::Palette::Rosybrown); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darksalmon", (void*)&Linear::Palette::Darksalmon); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lightcoral", (void*)&Linear::Palette::Lightcoral); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Salmon", (void*)&Linear::Palette::Salmon); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lightsalmon", (void*)&Linear::Palette::Lightsalmon); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Coral", (void*)&Linear::Palette::Coral); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Tomato", (void*)&Linear::Palette::Tomato); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Orangered", (void*)&Linear::Palette::Orangered); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Red", (void*)&Linear::Palette::Red); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Crimson", (void*)&Linear::Palette::Crimson); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Mediumvioletred", (void*)&Linear::Palette::Mediumvioletred); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Deeppink", (void*)&Linear::Palette::Deeppink); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Hotpink", (void*)&Linear::Palette::Hotpink); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Palevioletred", (void*)&Linear::Palette::Palevioletred); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Pink", (void*)&Linear::Palette::Pink); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Lightpink", (void*)&Linear::Palette::Lightpink); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Thistle", (void*)&Linear::Palette::Thistle); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Magenta", (void*)&Linear::Palette::Magenta); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Fuchsia", (void*)&Linear::Palette::Fuchsia); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Violet", (void*)&Linear::Palette::Violet); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Plum", (void*)&Linear::Palette::Plum); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Orchid", (void*)&Linear::Palette::Orchid); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Mediumorchid", (void*)&Linear::Palette::Mediumorchid); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkorchid", (void*)&Linear::Palette::Darkorchid); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkviolet", (void*)&Linear::Palette::Darkviolet); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkmagenta", (void*)&Linear::Palette::Darkmagenta); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Purple", (void*)&Linear::Palette::Purple); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Indigo", (void*)&Linear::Palette::Indigo); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Darkslateblue", (void*)&Linear::Palette::Darkslateblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Blueviolet", (void*)&Linear::Palette::Blueviolet); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Mediumpurple", (void*)&Linear::Palette::Mediumpurple); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Slateblue", (void*)&Linear::Palette::Slateblue); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF Mediumslateblue", (void*)&Linear::Palette::Mediumslateblue); assert(r >= 0);

			r = engine->RegisterGlobalProperty("const ColorF DefaultLetterbox", (void*)&Linear::Palette::DefaultLetterbox); assert(r >= 0);
			r = engine->RegisterGlobalProperty("const ColorF DefaultBackground", (void*)&Linear::Palette::DefaultBackground); assert(r >= 0);
		}
		r = engine->SetDefaultNamespace(""); assert(r >= 0);
	}
}
